[package]
name = "broadcast"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.163", features = ["derive"]}
serde_json = "1.0.96"
tokio = { version = "1.28.1", features = ["full"] }
